AllCops:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'coverage/**/*'
    - 'examples/**/*'
    - 'scripts/**/*'

Layout/EmptyLineBetweenDefs:
  NumberOfEmptyLines: [1,2]

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/LineLength:
  Max: 170

Metrics/ModuleLength:
  Max: 200

Metrics/ClassLength:
  Max: 200
